# Generated by Django 4.1.3 on 2022-12-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_secret_writer_delete_useraccount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Secret",
        ),
    ]
