# Generated by Django 4.1.3 on 2022-12-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="secret",
            old_name="writer",
            new_name="user",
        ),
    ]
