# Generated by Django 4.1.3 on 2022-12-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_rename_writer_secret_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secret",
            name="secretkey",
            field=models.TextField(unique=True),
        ),
    ]
