# Generated by Django 4.1.3 on 2022-12-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_alter_secret_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secret",
            name="user",
            field=models.TextField(),
        ),
    ]
